# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e104ecf6bbd82baefcba1617f61fd4201af79a17ba9d18dcc5a0bc3d69478aefc647968007420be0a09a7878991251fa200bcfd47e63ff276bafc38290489f

test:
  secret_key_base: 72c9fb0abd0a2f5e2a64968e1dbc9a690ef131417a3f42fd6e8a2a719978858fdd8475bcf990989721408a5aad8503039f5f2f0b9528b1a2efd0a78471c78d8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
